services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Domain\Loan\Calculator\LoanCalculatorInterface:
        alias: App\Domain\Loan\Calculator\EqualInstallmentsLoanCalculator
